apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-app
  template:
    metadata:
      labels:
        app: lms-app
    spec:
      containers:
      - name: lms-app
        image: 242201276768.dkr.ecr.us-east-1.amazonaws.com/lms-app:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: ecr-reg-cred
