version: "3.9"
services:
  web:
    build: .
    container_name: lms-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://lmsuser:lmspass@db:3306/lmsdb
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: lmsdb
      MYSQL_USER: lmsuser
      MYSQL_PASSWORD: lmspass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
