apiVersion: v1
kind: Service
metadata:
  name: lms-service
spec:
  type: LoadBalancer   # Use ClusterIP if only internal
  selector:
    app: lms-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
