# Generated by Django 5.0.1 on 2024-05-22 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0213_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ManyToManyField(related_name='subjects', to='learning.cls_name'),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 18, 43, 6, 341337)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='today',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 18, 43, 6, 378124)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 22, 18, 43, 6, 338638)),
        ),
        migrations.AlterField(
            model_name='shift_names',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 22, 18, 43, 6, 338638)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='half_daytime',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 5, 22, 18, 43, 6, 358507)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 5, 22, 18, 43, 6, 358507)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='late_mark_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 5, 22, 18, 43, 6, 358507)),
        ),
        migrations.AlterField(
            model_name='teacher_shifts',
            name='out_time',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 5, 22, 18, 43, 6, 358507)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 18, 43, 6, 350504)),
        ),
    ]
