# Generated by Django 5.2.4 on 2025-08-12 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0221_alter_employeeloginlogout_login_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeloginlogout",
            name="login_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 12, 11, 59, 59, 494188)
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="today",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 12, 11, 59, 59, 513714)
            ),
        ),
        migrations.AlterField(
            model_name="shift_names",
            name="end_time",
            field=models.TimeField(
                default=datetime.datetime(2025, 8, 12, 11, 59, 59, 491925)
            ),
        ),
        migrations.AlterField(
            model_name="shift_names",
            name="start_time",
            field=models.TimeField(
                default=datetime.datetime(2025, 8, 12, 11, 59, 59, 491925)
            ),
        ),
        migrations.AlterField(
            model_name="teacher_shifts",
            name="half_daytime",
            field=models.TimeField(
                verbose_name=datetime.datetime(2025, 8, 12, 11, 59, 59, 497937)
            ),
        ),
        migrations.AlterField(
            model_name="teacher_shifts",
            name="in_time",
            field=models.TimeField(
                verbose_name=datetime.datetime(2025, 8, 12, 11, 59, 59, 497937)
            ),
        ),
        migrations.AlterField(
            model_name="teacher_shifts",
            name="late_mark_time",
            field=models.TimeField(
                verbose_name=datetime.datetime(2025, 8, 12, 11, 59, 59, 497937)
            ),
        ),
        migrations.AlterField(
            model_name="teacher_shifts",
            name="out_time",
            field=models.TimeField(
                verbose_name=datetime.datetime(2025, 8, 12, 11, 59, 59, 497937)
            ),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="dob",
            field=models.DateField(
                default=datetime.datetime(2025, 8, 12, 11, 59, 59, 497937)
            ),
        ),
    ]
