# Generated by Django 5.2.4 on 2025-08-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0227_learning_hero"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Learning_Hero",
        ),
    ]
