# Generated by Django 5.2.4 on 2025-08-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0228_delete_learning_hero"),
    ]

    operations = [
        migrations.DeleteModel(
            name="hero",
        ),
    ]
